#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync, mkdirSync, unlinkSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { flattenDotPath, hashValue, diffCanonical } from './lib/diff.mjs';
import { buildArbKeyMap } from './lib/flatten.mjs';
import { buildArbJson } from './lib/transpile.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');

const CANONICAL = {
  'zh-TW': join(REPO_ROOT, 'i18n/canonical/zh-TW.json'),
  en: join(REPO_ROOT, 'i18n/canonical/en.json'),
  ja: join(REPO_ROOT, 'i18n/canonical/ja.json'),
};
const CACHE_PATH = join(REPO_ROOT, 'i18n/.i18n-cache.json');
const PENDING_PATH = join(REPO_ROOT, 'i18n/.pending-translations.md');
const WEB_MESSAGES_DIR = join(REPO_ROOT, 'src/messages');
const MOBILE_L10N_DIR = join(REPO_ROOT, 'mobile/lib/l10n');

// ── CLI parsing ──
const args = process.argv.slice(2);
const isDry = args.includes('--dry');

// ── Helpers ──
function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

function writeJson(path, data) {
  const dir = dirname(path);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(path, JSON.stringify(data, null, 2) + '\n', 'utf8');
}

function unflattenDotPath(flat) {
  const out = {};
  for (const [key, value] of Object.entries(flat)) {
    const parts = key.split('.');
    let cur = out;
    for (let i = 0; i < parts.length - 1; i++) {
      if (!(parts[i] in cur)) cur[parts[i]] = {};
      cur = cur[parts[i]];
    }
    cur[parts[parts.length - 1]] = value;
  }
  return out;
}

function buildPendingMarkdown({
  zhRaw,
  zhFlat,
  pendingEn,
  pendingJa,
  staleEn,
  staleJa,
  locked,
}) {
  const lockedList = Object.keys(locked || {});
  const listSection = (title, keys) => {
    if (keys.length === 0) return `## ${title}\n\n(none)\n`;
    const lines = keys.map((k) => `- \`${k}\` — zh: "${zhFlat[k]}"`);
    return `## ${title}\n\n${lines.join('\n')}\n`;
  };
  const staleSection = (title, keys, enOrJa) => {
    if (keys.length === 0) return `## ${title}\n\n(none)\n`;
    const lines = keys.map(
      (k) =>
        `- \`${k}\` — zh now: "${zhFlat[k]}" (review \`canonical/${enOrJa}.json\` for current translation)`
    );
    return `## ${title}\n\n${lines.join('\n')}\n`;
  };

  return `# Pending i18n Translations

Generated by \`i18n/scripts/sync.mjs\`. Canonical \`zh-TW.json\` has keys missing
(or changed) in \`en.json\` / \`ja.json\`.

**Workflow:**

1. Ask Claude (in the current Claude Code conversation) to translate the keys below.
2. Claude edits \`i18n/canonical/en.json\` and \`i18n/canonical/ja.json\` directly (巢狀 JSON，與 zh-TW 同結構).
3. Re-run \`npm run i18n:sync\` — this file auto-deletes when nothing is pending.

**Translation rules:**

- Preserve ICU placeholders (\`{name}\`, \`{count, plural, ...}\`) exactly.
- Tone: terse, verb-first, app-friendly (not formal).
- Labels / buttons: verb or noun phrase, not full sentences.
- Keep translations consistent with existing entries in the same canonical file.

## Source (zh-TW, full canonical for context)

\`\`\`json
${JSON.stringify(zhRaw, null, 2)}
\`\`\`

${listSection('Keys needing English translation (missing in en.json)', pendingEn)}
${listSection('Keys needing Japanese translation (missing in ja.json)', pendingJa)}
${staleSection('Possibly stale English (zh-TW changed)', staleEn, 'en')}
${staleSection('Possibly stale Japanese (zh-TW changed)', staleJa, 'ja')}
## Locked keys (do not retranslate)

${lockedList.length ? lockedList.map((k) => `- \`${k}\``).join('\n') : '(none)'}
`;
}

// ── Main ──
async function main() {
  console.log('📖 讀取 canonical...');
  const zhRaw = readJson(CANONICAL['zh-TW']);
  const zhFlat = flattenDotPath(zhRaw);
  const cache = existsSync(CACHE_PATH)
    ? readJson(CACHE_PATH)
    : { version: 1, hashes: {}, locked: {} };
  const locked = cache.locked || {};

  // 1. Diff vs last-synced cache
  const diff = diffCanonical(cache.hashes, zhFlat);
  console.log(`📊 Diff: +${diff.added.length} ~${diff.changed.length} -${diff.removed.length}`);
  if (diff.added.length) console.log('   新增:', diff.added.slice(0, 10));
  if (diff.changed.length) console.log('   變動:', diff.changed.slice(0, 10));
  if (diff.removed.length) console.log('   刪除:', diff.removed.slice(0, 10));

  // 2. Read current en/ja
  const enFlat = flattenDotPath(readJson(CANONICAL.en));
  const jaFlat = flattenDotPath(readJson(CANONICAL.ja));

  // 3. Drop removed keys from en/ja
  for (const k of diff.removed) {
    delete enFlat[k];
    delete jaFlat[k];
  }

  // 4. Compute pending (strictly: missing keys — this is independent of cache so
  //    we detect untranslated state even after cache has been updated)
  const pendingEn = Object.keys(zhFlat).filter((k) => !locked[k] && !(k in enFlat));
  const pendingJa = Object.keys(zhFlat).filter((k) => !locked[k] && !(k in jaFlat));

  // 5. Compute stale (informational: zh changed, en/ja still has old translation)
  const staleEn = diff.changed.filter((k) => !locked[k] && k in enFlat);
  const staleJa = diff.changed.filter((k) => !locked[k] && k in jaFlat);

  if (isDry) {
    console.log('💡 --dry 模式...');
    for (const lang of ['zh-TW', 'en', 'ja']) {
      const msgPath = join(WEB_MESSAGES_DIR, `${lang}.json`);
      if (!existsSync(msgPath)) {
        console.error(`❌ 生成檔缺少: ${msgPath}`);
        process.exit(1);
      }
    }
    const outOfSync =
      diff.added.length + diff.changed.length + diff.removed.length > 0;
    if (outOfSync || pendingEn.length > 0 || pendingJa.length > 0 || existsSync(PENDING_PATH)) {
      console.error(
        '❌ canonical 不同步或有 pending 翻譯，請跑 `npm run i18n:sync` 並處理 pending'
      );
      process.exit(1);
    }
    console.log('✅ In sync');
    return;
  }

  // 6. Write or clear pending file
  const hasPending =
    pendingEn.length > 0 ||
    pendingJa.length > 0 ||
    staleEn.length > 0 ||
    staleJa.length > 0;
  if (hasPending) {
    writeFileSync(
      PENDING_PATH,
      buildPendingMarkdown({ zhRaw, zhFlat, pendingEn, pendingJa, staleEn, staleJa, locked }),
      'utf8'
    );
    console.log(`📝 Wrote ${PENDING_PATH}`);
  } else if (existsSync(PENDING_PATH)) {
    unlinkSync(PENDING_PATH);
    console.log(`🗑  Removed stale ${PENDING_PATH}`);
  }

  // 7. Write canonical en/ja back (normalized — handles removed keys)
  writeJson(CANONICAL.en, unflattenDotPath(enFlat));
  writeJson(CANONICAL.ja, unflattenDotPath(jaFlat));

  // 8. Transpile → Web messages (merge zh as fallback for missing keys)
  const mergedEn = { ...zhFlat, ...enFlat };
  const mergedJa = { ...zhFlat, ...jaFlat };
  writeJson(join(WEB_MESSAGES_DIR, 'zh-TW.json'), unflattenDotPath(zhFlat));
  writeJson(join(WEB_MESSAGES_DIR, 'en.json'), unflattenDotPath(mergedEn));
  writeJson(join(WEB_MESSAGES_DIR, 'ja.json'), unflattenDotPath(mergedJa));
  console.log('📝 Wrote src/messages/*.json');

  // 9. Transpile → Mobile ARB
  //    gen-l10n 要求 template_arb_file 的 locale 是 base locale（zh，不含 country code），
  //    所以 mobile 上 'zh' 就是繁中（與 web 上的 'zh-TW' 等價）。
  const zhArb = buildArbJson(buildArbKeyMap(zhFlat), 'zh');
  const enArb = buildArbJson(buildArbKeyMap(mergedEn), 'en');
  const jaArb = buildArbJson(buildArbKeyMap(mergedJa), 'ja');
  writeJson(join(MOBILE_L10N_DIR, 'app_zh.arb'), zhArb);
  writeJson(join(MOBILE_L10N_DIR, 'app_en.arb'), enArb);
  writeJson(join(MOBILE_L10N_DIR, 'app_ja.arb'), jaArb);
  console.log('📱 Wrote mobile/lib/l10n/*.arb');

  // 10. Update cache to match current zh
  const newHashes = {};
  for (const [k, v] of Object.entries(zhFlat)) {
    newHashes[k] = hashValue(v);
  }
  cache.hashes = newHashes;
  writeJson(CACHE_PATH, cache);
  console.log('💾 Cache updated');

  if (pendingEn.length + pendingJa.length > 0) {
    console.log(
      `\n⚠️  ${pendingEn.length} en + ${pendingJa.length} ja key(s) pending translation.`
    );
    console.log(`   See ${PENDING_PATH}`);
    console.log('   Ask Claude to translate, then re-run sync.\n');
  } else if (staleEn.length + staleJa.length > 0) {
    console.log(
      `\n⚠️  ${staleEn.length} en + ${staleJa.length} ja key(s) may be stale (zh-TW changed).`
    );
    console.log(`   See ${PENDING_PATH} if you want to refresh them.\n`);
  } else {
    console.log('✅ Sync 完成');
  }
}

main().catch((err) => {
  console.error('❌', err.message);
  if (process.env.DEBUG) console.error(err.stack);
  process.exit(1);
});
